version: 2.1

# testing as per incident https://status.circleci.com/incidents/p9dmh9b6lh90

orbs:
  flow: kelvintaywl/control-flow@0.1.1

executors:
  docker-sm:
    parameters:
      img:
        type: string
        default: cimg/base:current
    docker:
      - image: << parameters.img >>
    resource_class: small

jobs:
  noop:
    executor: docker-sm
    steps:
      - checkout

workflows:
  aaa:
    jobs:
      - noop
      - flow/approve-workflow:
          workflow-name: bbb
          job-name: start
          requires:
            - noop
  bbb:
    jobs:
      - start:
          type: approval
      - noop:
          requires:
            - start
